### ISSUE TITLE
Any hints on Obj-C support.

### ISSUE THREAD

**Issue by jogboms** [Flutterwave/Rave#1]
I currently have the need to implement the library within an Obj-C environment for a cross-platform app. I'm not much of an iOS dev.
Skipping the Framework integration and all, Any pointers on how this could be achieved?

**Comment by temiadesina** [comment]
Hi, @jogboms we are working on supporting Obj-C we have it on the roadmap and would let you know once we have completed it.

**Comment by Corvus97** [comment]
Hello @jogboms ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
