### ISSUE TITLE
Rave compiled with older version of Swift language (4.1/4.2)

### ISSUE THREAD

**Issue by dammynex** [Flutterwave/Rave#10]
Getting this error using xcode 11.2

Rave.framework/Rave compiled with older version of Swift language (4.1/4.2) than previous files (5 or later) file

**Comment by Corvus97** [comment]
Hello @dammynex ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
