### ISSUE TITLE
Too many depenedencies

### ISSUE THREAD

**Issue by jerryOkafor** [Flutterwave/Rave#11]
There is a need to upgrade this SDK and strip off the many dependencies such as Alamofire. You can depend on the base framework URLRequest. This will ease integration and improve the memory footprint of the SDK.

**Comment by Corvus97** [comment]
Hello @jerryOkafor ,

Apologies for the late reply.

Thank you for bringing this to our attention.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
