### ISSUE TITLE
Updated your library to support swift 5 and exposed RavePayManager to support Objc

### ISSUE THREAD

**Issue by MohammedBashiru** [Flutterwave/Rave#12]
### Need Permission to create PR

I needed to use this library so I updated it with all dependencies to support SWIFT 5 and Objc
I need permission to push changes or create PR @solejay

**Comment by Nilesh04** [comment]
Hello @MohammedBashiru 
I am also facing dependencies issue and it is not building for Generic iOS Device. Could you please share your updates with me.
Thank you :)

**Comment by MohammedBashiru** [comment]
@Nilesh04 what version of swift is your project? have you tried setting it to swift 5 ? could you also tell more about the dependencies having issues with ?

**Comment by Nilesh04** [comment]
@MohammedBashiru I am getting same issue, I am using Xcode 11.2.1

**Comment by ThandavaSiva** [comment]
> Hello @MohammedBashiru
> I am also facing dependencies issue and it is not building for Generic iOS Device. Could you please share your updates with me.
> Thank you :)

Hi @Nilesh04 ,
Did you got solution for this issue.
What did you done for fixing this issue.

**Comment by MohammedBashiru** [comment]
@Nilesh04  @ThandavaSiva 
check this 
https://github.com/Flutterwave/Rave/issues/16#issuecomment-586582383

**Comment by Corvus97** [comment]
Hello @MohammedBashiru and @Nilesh04 ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
