### ISSUE TITLE
No such module 'Shimmer' error

### ISSUE THREAD

**Issue by ankitpansuria** [Flutterwave/Rave#14]
I am trying to integrate Rave with my project. My project uses Swift 5 and X Code 11.3. I have followed the steps provided here -> https://developer.flutterwave.com/docs/ios

I installed all dependent third party libraries required by Rave SDK to my project using pod.

After adding Rave.xcodeproj to my project I tried adding all installed pod frameworks to "Rave > General > Linked Frameworks and Library" but they seem to be already present and grayed out. Clicking on + icon and search shows empty result.

![image](https://user-images.githubusercontent.com/58808742/73134939-95a7db80-4062-11ea-8c95-6df49345bffb.png)

![image](https://user-images.githubusercontent.com/58808742/73134942-a2c4ca80-4062-11ea-8aa8-496e1c32bda0.png)

Further when I build my project it gives following error:

![image](https://user-images.githubusercontent.com/58808742/73134949-be2fd580-4062-11ea-987c-d91ac9c3a9a5.png)

![image](https://user-images.githubusercontent.com/58808742/73134958-c851d400-4062-11ea-939d-5d9011ca3131.png)

**Comment by ThandavaSiva** [comment]
@ankitpansuria, Did you successfully integrated Rave SDK in you project?, if you done please guide me how to integrate SDK.

**Comment by Corvus97** [comment]
Hello @ankitpansuria ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
