### ISSUE TITLE
i cant create my application ipa file using Rave with Swift5

### ISSUE THREAD

**Issue by ThandavaSiva** [Flutterwave/Rave#15]
Can you please guide me how to integrate rave in swift 5 in xcode11.3.1

**Comment by ThandavaSiva** [comment]
any one is there for supporting us to fix this issues

**Comment by Corvus97** [comment]
Hello @ThandavaSiva ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
