### ISSUE TITLE
Hello @MohammedBashiru

### ISSUE THREAD

**Issue by ThandavaSiva** [Flutterwave/Rave#16]
Hello @MohammedBashiru, @temiadesina, @MaestroJolly
I am also facing dependencies issue and it is not building for Generic iOS Device. Could you please share your updates with me.

I am using Swift 5 and XCode 11.3.1
I am using your code : https://github.com/MohammedBashiru/Rave

Can you please guide me how to integrate Rave SDK in my project
I followed https://developer.flutterwave.com/docs/ios this document but i am still getting dependencies issues Please help on this

**Comment by MohammedBashiru** [comment]
Open the rave cocoa pod project. And use Xcode to update code to swift 5.
For some dependencies, you would have to update manually that's changing versions and fixing deprecated syntax

You then have to build the library first for Generic iOS devices and rename it to **Rave-dev.framework** and Simulators  and rename also to ( **Rave-sim.framework** )
Once you are done with that. 

Creating FAT File by using the command below.
 **lipo -create </Points to dir for Rave-dev.framework/Rave/> <points to dir for Rave-sim.framework/Rave> <...> -output <Where to save new Rave bin>**

full command 
**lipo -create <file1> <file2> <-output>** withotu < & >

After that combine the 

once you are done with that copy the new generated **Rave** bin file and override it with existing one in Rave-dev.framework

open **Rave-sim.framework/Modules/swiftmodules** and copy everything there to the same location in Rave-dev.framework

and use Rave-dev.framework in your project.
This now allows you to build for IOS devices and simulators.

**Comment by ThandavaSiva** [comment]
@MohammedBashiru 
Thanks for your info
after FAT process now i am getting below bitcode issue. if you got this type of issue please guide me to fix this.
"bitcode bundle could not be generated because was built without full bitcode. in frameworks and dylib for bitcode must be generated from xcode archive or install build file for architecture arm64"

**Comment by MohammedBashiru** [comment]
@ThandavaSiva Sorry I didn’t get such issue. I could have easily shared my version with you but it’s heavily modified.

When do you get the above error. Building the framework or building your project or testing on device ??

**Comment by ThandavaSiva** [comment]
@MohammedBashiru , issue happen when i am trying to archive the build but it showing bitcode issue

**Comment by ThandavaSiva** [comment]
@solejay Can you please help on this

**Comment by ThandavaSiva** [comment]
<img width="750" alt="Screenshot 2020-02-22 at 9 25 01 PM" src="https://user-images.githubusercontent.com/24223418/75095360-df300b80-55b9-11ea-9068-cb3babe49a05.png">

**Comment by Corvus97** [comment]
Hello @ThandavaSiva and @MohammedBashiru ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
