### ISSUE TITLE
SDK keeps crashing while trying to make payment.

### ISSUE THREAD

**Issue by meshileya** [Flutterwave/Rave#17]
```
func getEncryptionKey(_ secretKey:String)->String {
    let md5Data = MD5(string:secretKey)
    let md5Hex =  md5Data!.map { String(format: "%02hhx", $0) }.joined()
    
    var secretKeyHex = ""
    
    if secretKey.contains("FLWSECK-") {
        secretKeyHex = secretKey.replacingOccurrences(of: "FLWSECK-", with: "")
    }
    if secretKey.contains("-X") {
        secretKeyHex = secretKeyHex.replacingOccurrences(of: "-X", with: "")
    }
    
    **let index = secretKeyHex.index(secretKeyHex.startIndex, offsetBy: 12)**
    let first12 = secretKeyHex.substring(to: index)
    
    let last12 = md5Hex.substring(from:md5Hex.index(md5Hex.endIndex, offsetBy: -12))
    return first12 + last12
    
}
```

The crash actually is array out on index

**Comment by avinashvaghasiya** [comment]
@meshileya I getting same error so what are changes for the same

**Comment by meshileya** [comment]
Had to just use my live key for the test instead of test key.

**Comment by Corvus97** [comment]
Hello @meshileya ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
