### ISSUE TITLE
Shows HTML text after payment done 

### ISSUE THREAD

**Issue by deepakbhati99** [Flutterwave/Rave#18]
on Rave iOS SDK, once payment done with success, on same page i see some HTML. text.
and after 1-2 seconds its gone.
why its showing ?? can you please help me ?

**Comment by Corvus97** [comment]
Hello @deepakbhati99,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
