### ISSUE TITLE
We could not charge this card. Reason: Charge not yet supported for country AD

### ISSUE THREAD

**Issue by sourcenetsecommerce** [Flutterwave/Rave#19]
PWe could not charge this card. Reason: Charge not yet supported for country AD

Please help me fix this

**Comment by Corvus97** [comment]
Hello @sourcenetsecommerce,

Thanks for bringing this to our attention.

Please note that this SDK is no longer supported by the Team.

Kindly make use of the new SDK here - https://github.com/Flutterwave/RaveSDK

Also, you can check this article on country codes accepted for international payments - https://developer.flutterwave.com/v2.0/docs/multicurrency-payments

Best regards,
Cornelius
