### ISSUE TITLE
Bugs...

### ISSUE THREAD

**Issue by Faktorealchik** [Flutterwave/Rave#2]
1. where is readme ? 
2. now after updates sdk not working properly. 
trying to buy, sdk gets an error - "an error occured while attempting to decrypt some parameters" 

one month ago it works well.

**Comment by obaro** [comment]
@Faktorealchik did you get this to work? This is 8 months later, and I'm getting the same bug

**Comment by Faktorealchik** [comment]
@obaro Hello, we did not finish that project with flutterwave, so this is not works

**Comment by AhmadBashir-io** [comment]
@Faktorealchik  @obaro try checking if the payload your are sending to be encrypted is stringified ... for example ... 
`var data = JSON.stringify( payload ) `  before passing it to the encrypt function ... for example ...  `encrypt= (key, data) 
// Rave encryption found here -> https://developer.flutterwave.com/reference#rave-encryption
`[ https://developer.flutterwave.com/reference#rave-encryption](url)

**Comment by ighotouch** [comment]
@Faktorealchik ensure you are using the encryptionkey from the rave dashboard
