### ISSUE TITLE
Pod

### ISSUE THREAD

**Issue by Faktorealchik** [Flutterwave/Rave#3]
Make it pod. Why you just leave it with .framework ?

**Comment by Corvus97** [comment]
Hello @Faktorealchik ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
