### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Faktorealchik** [Flutterwave/Rave#4]
Why you have commented code, why you dont delete it? Why you are not observe code of conduction ? please, repair your code to readable format....

**Comment by Corvus97** [comment]
Hello @Faktorealchik ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
