### ISSUE TITLE
Diamondbank is not listed while payment using Bank.

### ISSUE THREAD

**Issue by aryankonstant** [Flutterwave/Rave#5]
@flutterwavedeveloper @temiadesina 
Can you please help me out on this issue. Everything is working fine except the **Diamondbank** is not listed while payment using BANK.

**Comment by temiadesina** [comment]
Hi, @aryankonstant Diamond bank is not an available DIrect bank payment option now. When it becomes available we did let you know.

**Comment by Corvus97** [comment]
Hello @aryankonstant ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
