### ISSUE TITLE
error: Charge not yet supported for country RW ? 

### ISSUE THREAD

**Issue by devendroid** [Flutterwave/Rave#6]
When i'm trying with county code RW and currency code RWF for Rwanda country:
getting response:
{
data = "";
message = "Charge not yet supported for country RW";
status = error;
}

While Flutterwave works in Rwanda, I using in android also without any issue,
then why its not working in iOS?

**Comment by MaestroJolly** [comment]
Hi devendroid,

For Rwanda payments, please use NG as the country not RW and use currency as RWF.

**Comment by devendroid** [comment]
Thanks @MaestroJolly, Now its working.
