### ISSUE TITLE
Could not find module 'Rave' for target 'i386-apple-ios-simulator'; found: arm64, arm

### ISSUE THREAD

**Issue by manoharsinghrawat-cedcoss** [Flutterwave/Rave#7]
I am getting this issue while running app in xcode 11. I have already migrated the code to swift 4.2 and integrated the payment gateway in my project. It is running fine in debug version while it's giving following error in release version:
Could not find module 'Rave' for target 'i386-apple-ios-simulator'; found: arm64, arm

**Comment by MarcosiOSdev** [comment]
Did you bugfix ?
I need know too :/

**Comment by Corvus97** [comment]
Hello @MarcosiOSdev and @manoharsinghrawat-cedcoss ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
