### ISSUE TITLE
Fatal Error: String Index Is Out of Bounds

### ISSUE THREAD

**Issue by fredrickabayie** [Flutterwave/Rave#8]
Test keys on IOS produce, `Fatal Error: String Index Is Out of Bounds` from the below function, even though staging is enabled. 

`func getEncryptionKey(_ secretKey:String)->String {
    let md5Data = MD5(string:secretKey)
    let md5Hex =  md5Data!.map { String(format: "%02hhx", $0) }.joined()
  
    var secretKeyHex = ""
    
    if secretKey.contains("FLWSECK-") {
        secretKeyHex = secretKey.replacingOccurrences(of: "FLWSECK-", with: "")
    }
    if secretKey.contains("-X") {
        secretKeyHex = secretKeyHex.replacingOccurrences(of: "-X", with: "")
    }
    
    let index = secretKeyHex.index(secretKeyHex.startIndex, offsetBy: 12)
    let first12 = secretKeyHex.substring(to: index)
    
    let last12 = md5Hex.substring(from:md5Hex.index(md5Hex.endIndex, offsetBy: -12))
    return first12 + last12
    
}`

The above function is for live key encryption and the SDK doesn't seem to have the function to encrypt test keys, hence the live key encryption function is used for both and since the format for test and live keys differ that's when `secretKeyHex` is always an empty string.

Live keys work fine...

**Comment by Corvus97** [comment]
Hello @fredrickabayie ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
