### ISSUE TITLE
dyld: Library not loaded: @rpath/Rave.framework/Rave

### ISSUE THREAD

**Issue by devd77** [Flutterwave/Rave#9]
in simulator working properly, but when i/m running on real device ..it's crashed on launch.
LOGS:
dyld: Library not loaded: @rpath/Rave.framework/Rave
  Referenced from: /private/var/containers/Bundle/Application/2509AB63-0CD1-485C-A870-5605E34CB0ED/Journi Driver.app/Journi Driver
  Reason: image not found

**Comment by Corvus97** [comment]
Hello @devd77 ,

Apologies for the late reply.

Kindly be advised that this SDK is no longer supported by the Team. Please use the new SDK (https://github.com/Flutterwave/RaveSDK) for a better experience.

Also, you can join our discussion on our forum(https://developer.flutterwave.com/discuss) for more tips on issue resolution.

Best regards,
Cornelius
